-- AlterTable
ALTER TABLE `character` ADD COLUMN `gold` INTEGER NOT NULL DEFAULT 500,
    ADD COLUMN `pendingLineages` INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN `pendingPath` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `pendingSkills` INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN `pendingTrainings` INTEGER NOT NULL DEFAULT 1;
